openapi: 3.0.1
info:
  title: Catalog - Weather
  description: Weather lookup API. Managed by team-catalog.
  version: '1.0'
servers:
  - url: https://apim-networked-a.azure-api.net/catalog/weather
paths:
  '/weather/{city}':
    get:
      summary: Get weather
      operationId: get-weather
      parameters:
        - name: city
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]